// data.js — Data access layer for Game News Round-Up.
//
// Round-ups live as per-day JSON files under news/<YYYY>/<MM>/<YYYY-MM-DD>.json,
// indexed by news/index.json (newest first). Generated by scripts/import-discord.mjs.
//
// `roundups` holds the lightweight index entries (date, title, story_count,
// section_ids, top_titles). Full sections are fetched on demand by loadDay() and
// merged into the matching index entry, so pages that need full story data must
// await the relevant day first (the App bootstrap handles this).
window.GNRU = {

  roundups: [],      // index entries, newest first
  _dayCache: {},     // date -> in-flight/loaded promise
  _indexLoaded: false,

  async loadIndex() {
    if (this._indexLoaded) return this.roundups;
    const res = await fetch('/news/index.json');
    if (!res.ok) throw new Error(`Failed to load news index (${res.status})`);
    this.roundups = await res.json();
    this._indexLoaded = true;
    return this.roundups;
  },

  // True once the manifest is available (loaded or seeded from the bootstrap island).
  hasIndex() {
    return this._indexLoaded && this.roundups.length > 0;
  },

  // Fetch a day's full round-up and merge its sections into the index entry.
  async loadDay(date) {
    if (!date) return null;
    if (this._dayCache[date]) return this._dayCache[date];
    const entry = this.roundups.find(r => r.date === date);
    const [y, m] = date.split('-');
    const promise = fetch(`/news/${y}/${m}/${date}.json`)
      .then(res => {
        if (!res.ok) throw new Error(`Failed to load ${date} (${res.status})`);
        return res.json();
      })
      .then(full => {
        if (entry) Object.assign(entry, full); // merge sections/video/summary in place
        return entry || full;
      });
    this._dayCache[date] = promise;
    return promise;
  },

  // Has this day's full section data been loaded yet?
  isDayLoaded(date) {
    const entry = this.roundups.find(r => r.date === date);
    return !!(entry && entry.sections);
  },

  getLatest() {
    return this.roundups.find(r => r.status === 'published') || this.roundups[0];
  },

  getByDate(date) {
    return this.roundups.find(r => r.date === date);
  },

  formatDate(dateStr) {
    const d = new Date(dateStr + 'T12:00:00Z');
    return d.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
  },

  formatDateShort(dateStr) {
    const d = new Date(dateStr + 'T12:00:00Z');
    return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  },

  formatDateMed(dateStr) {
    const d = new Date(dateStr + 'T12:00:00Z');
    return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
  },

  groupByMonth(roundups) {
    const groups = {};
    roundups.forEach(r => {
      const key = r.date.slice(0, 7);
      if (!groups[key]) groups[key] = [];
      groups[key].push(r);
    });
    return groups;
  },

  // Works on a full round-up (sum its sections) or an index entry (story_count).
  getTotalStories(roundup) {
    if (roundup.sections) return roundup.sections.reduce((sum, s) => sum + s.items.length, 0);
    return roundup.story_count || 0;
  },

  getSectionIds(roundup) {
    if (roundup.sections) return roundup.sections.filter(s => s.items.length > 0).map(s => s.id);
    return roundup.section_ids || [];
  }
};

// Seed from the pre-rendered page's bootstrap island so the app boots with the
// manifest (and the current day) already in memory — no fetch, no Loading flash.
// The island is { index: [...entries], day: <full round-up>|null } embedded by the
// static-page generator (scripts/lib/render-html.mjs). Absent in dev = normal fetch.
(function seedFromBootstrap() {
  const el = document.getElementById('gnr-bootstrap');
  if (!el) return;
  let data;
  try { data = JSON.parse(el.textContent); } catch (e) { return; }
  if (!data || !Array.isArray(data.index) || data.index.length === 0) return;
  window.GNRU.roundups = data.index;
  window.GNRU._indexLoaded = true;
  if (data.day && data.day.date) {
    const entry = window.GNRU.roundups.find(r => r.date === data.day.date);
    if (entry) Object.assign(entry, data.day);
    window.GNRU._dayCache[data.day.date] = Promise.resolve(entry || data.day);
  }
})();
